### ISSUE TITLE
Error during first run

### ISSUE THREAD

**Issue by dvoulanas** [gem-library/gem#21]
Invalid MEX-file 'C:\Program Files\MATLAB\R2022b\toolbox\gem\gem\gem_mex.mexw64': A dynamic link library (DLL)
initialization routine failed.

Error in gem (line 114)
                        this.objectIdentifier = gem_mex('newFromMatlab', full(varargin{1}), gem.workingPrecision);

I am using matlab 2022b on windows 10

Thanks in advance!

**Comment by jdbancal** [comment]
Hmm, hard to guess which DLL Windows is not finding... Does adding the following [libgomp_64-1.dll](https://www.swisstransfer.com/d/5636f47b-29b3-477d-aea2-1cf6bc3b1928) library in the folder next to `gem_mex.mexw64` help? (link valid until 2023-06-12 at 10:31 CET)

**Comment by dvoulanas** [comment]
No it doesnt work.
Could you provide with list of the needed dlls? so I can track the required dependencies
My system variable PATH got zapped while trying to do another thing in my computer. I believe I got the original PATH restored but I am no sure if I got everything.

**Comment by jdbancal** [comment]
According to the command `objdump --private-headers gem_mex.mexw64 | grep DLL`, here is the list of DLLs needed by the build.
```
	DLL
 vma:            Hint    Temps     Avant    DLL       Premier
	DLL Name: libmex.dll
	DLL Name: libmx.dll
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: USER32.dll
```
Indeed `libgomp_64-1.dll` doesn't seem to be needed, so it's probably normal that adding it to the folder didn't change anything.

I would expect the first two libraries `libmex` and `libmx` to be part of Matlab, and the three remaining ones to be part of your Windows installation. Maybe it would be good to check whether these libraries are respectively in your Matlab install and in your system?

**Comment by dvoulanas** [comment]
I placed all those dlls into the gem_mex.mexw64 folder but still the same error. Maybe this is a compiler issue?
msvcrt.dll is only dll that wasn't present in my computer at all. I downloaded it from a reliable site.
I am out of ideas.

**Comment by jdbancal** [comment]
Ok, if `msvcrt.dll` is not in your system we might have a lead! According to [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Windows_library_files?wprov=sfla1), msvcrt.dll is a library that implements the standard C functions, and it is used by the MinGW compiler when linking C++ libraries (which is the case here). Unfortunately, all versions of Windows don't seem to come with an implementation of the library...

It seems that the common approach is for each application to bring their own version of msvcrt.dll that they were built with... I'm not sure I understand what is the point of having a shared library in this case (?), but I'll try to do this as soon as possible. In the mean time, it doesn't seem very advisable to download a lone dll, even from a trusted site (dlls generally come in families to form a consistent environment). Rather, the advised solution seems to be to install Windows's own package that contains the libraries suited to your system. From what I understand, this can be found [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by dvoulanas** [comment]
I believe I have all the libraries in the webpage you suggested installed. I reinstalled everything but still that particular file doesn't show up. I find this weird. I also have the MinGW compiler installed in both x96 and x64 versions. Finally, I did a SCF run to fix my files but still nothing when I tried to run GEM.

**Comment by dvoulanas** [comment]
![image](https://github.com/gem-library/gem/assets/40898960/216768fe-d29a-41b2-98dc-8996649594e2)
![image](https://github.com/gem-library/gem/assets/40898960/6fe04794-07cb-4c33-a675-a237a27def5e)

It's actually present in the SystemWOW64 and System32 folder. I don't know why windows search doesn't find it. I had look into the folder by myself.

GEM still doesn't want to compile though. Maybe the problem now isn't with the msvcrt.dll file.

**Comment by jdbancal** [comment]
Thanks for the feedback! I see that you have some versions of `msvcrt.dll` in your system indeed. When you say that GEM couldn't compile, does it mean that you tried to follow the steps described [here](https://gem-library.github.io/gem/docs/compilationInstructions.html) and something failed along the way?

**Comment by dvoulanas** [comment]
I followed the two first paragraphs of this:https://gem-library.github.io/gem/docs/installation.html
By compile I meant the mex compilation.
Compiling from source will be the last card to play.

**Comment by jdbancal** [comment]
Thank you for the clarification.
Ok, I managed to install a fresh Windows 11 with Matlab 2023a, and I observe the exact same message you reported when calling `gem(1)`. This should allow me to look more in details into what is going on here, I'll keep you posted.

**Comment by jdbancal** [comment]
Windows confirms that the binary only relies on the 5 DLLs we identified
![image](https://github.com/gem-library/gem/assets/5440791/f8063405-06b0-4971-bdb8-684689c23c02)

**Comment by jdbancal** [comment]
Well, Windows' DLLs seem to be quite a mess. Apparently, there is not even a standard C++ library that is forward compatible... So I guess it is time for a rebuild.

A lot of things have changed as far a building GNU software on Windows with autotools, and unfortunately easy support is not yet available, although things seem to be moving in the right direction. Anyway, here is a [freshly compiled](https://www.swisstransfer.com/d/85a571a7-29ae-4495-8bb1-60b986b50fac) version of the GEM Library for testing purpose (link valid until 2023-06-25 at 2:27 CET). Since I have only access to the latest Windows 11 and Matlab 2023a, this is what it was made with. I only used gcc 6.3, so the result should however be compatible with a number of earlier Matlab versions though (Matlab has been supporting this compiler for some time already).

I suspect that the way to go and try it would be as follows:
- In Matlab's Add-Ons, install MinGW (called "MATLAB Support for MinGW-w64 C/C++ Compiler")
- Add the `gem` subfolder of the above downloadable to the path and see what comes out when calling `gem(1)` or something like that

**Comment by dvoulanas** [comment]
Yes now it is working! Thank you very much for your effort in total.
Since you mentioned that this is for testing purposes so I guess you are going to make a final one.
Shouldn't be better for me to compile from source though?

**Comment by jdbancal** [comment]
Great! Thanks for checking, I'm glad to hear that the new build scheme works!

Yes, it was a test because I couldn't have access to a machine with your characteristics (Windows 11 with Matlab 2022b), so couldn't predict how it would behave. But since it works there won't be further changes, what you have now is the final thing, you can work with this :)

I will however prepare a new release that include this new build scheme (with updated website instructions as well). This should avoid any further incompatibility issues with Windows, at least until Matlab supports a C++ compiler with UCRT.

For info, up to now, Matlab only supported GCC version 6.3.0 (first released in Dec. 2016). The very last version of Matlab 2023a is the first one to [support GCC version 8.1](https://www.mathworks.com/support/requirements/supported-compilers.html) (first released in May 2018). There are distributions of [GCC 11.2](https://winlibs.com/) that support UCRT (first released in [July 2021](https://gcc.gnu.org/releases.html)). UCRT was first [introduced by Microsoft](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/) in 2015.

I'll close this issue once the new release is out.

**Comment by jdbancal** [comment]
The new binaries and updated install instructions are now available on the [official page](https://github.com/gem-library/gem/releases/tag/v2.0.3). Closing this issue.
